name: Test and Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'The release should be an experimental release'
        default: 'NO'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-version: # See https://endoflife.date/docker-engine / https://download.docker.com/linux/static/stable/x86_64/
          - "25.0" # 2024-01 --> EOL ?
          - "29"   # 2025-11 --> EOL ?
      fail-fast: false
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Set up Docker
        uses: docker/setup-docker-action@b2189fbf2a6592b51fee7cdd93ee2bfaeba733db # v5.1.0
        with:
          version: 'type=image,tag=${{ matrix.docker-version }}'
      - name: Test with Gradle
        run: ./gradlew assemble check

  githubRelease:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Release with Gradle
        run: ./gradlew githubRelease
        env:
          GITHUB_USER: "gocd-contrib"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PRERELEASE: "${{ github.event.inputs.prerelease }}"
